server:
  port: 8081

spring:
  application:
    name: "todo-api"
  datasource:
    url: jdbc:mysql://localhost:3307/mydb?allowPublicKeyRetrieval=true
    username: root
    password: juntae1111

  jpa:
    show-sql: false