server:
  port: 8081


spring:
  application:
    name: "todo-api"
  datasource:
    url: jdbc:mysql://localhost:3307/mydb?allowPublicKeyRetrieval=true
    username: rororo
    password: qwer

  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
